### ISSUE TITLE
Step Y Axis missing Label.  Bubble Indicator cut off at top.

### ISSUE THREAD

**Issue by PlymouthRock** [aeyrium/bezier-chart#34] opened 2019-08-11 12:06 UTC
![chart-with-step-y-axis](https://user-images.githubusercontent.com/2496106/62833153-e0927b80-bc07-11e9-9946-b7f43636956e.jpg)

We're having an issue when setting a Custom Scale chart to display the Y axis with steps set to 2.

- The step number below the top indicator is missing.  This only happens when doing a non-debug build.
- The bubble indicator is cut off at the top

Thank you for your efforts on this widget!

`Container(
              color: Colors.transparent,
              height: 250,
              child: BezierChart(
                bezierChartScale: BezierChartScale.CUSTOM,
                xAxisCustomValues: const [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
                footerValueBuilder: (double value) {

                  int hour = value.toInt();

                  if(hour == 0) {
                    return '12 am';
                  } else if (hour < 12) {
                    return '$hour am';
                  } else {
                    return '${hour > 12 ? hour - 12 : hour} pm';
                  }
                },
                series: [
                  BezierLine(
                    lineColor: Colors.blue,
                    lineStrokeWidth: 2.0,
                    label: "feet",
                    data: dataPoints,
                  ),
                ],
                config: BezierChartConfig(
                  verticalIndicatorStrokeWidth: 2.0,
                  verticalIndicatorColor: Colors.grey.shade800,
                  bubbleIndicatorColor: Colors.grey.shade800,
                  displayYAxis: true,
                  startYAxisFromNonZeroValue: false,
                  stepsYAxis: 2,
                  contentWidth: 1400,
                  bubbleIndicatorTitleStyle: TextStyle(
                    color: Colors.grey.shade800,
                  ),
                  bubbleIndicatorValueStyle: TextStyle(
                    color: Colors.white
                  ),
                  yAxisTextStyle: TextStyle (
                    fontSize: 14
                  ),
                  xAxisTextStyle: TextStyle (
                    fontSize: 14
                  ),
                ),
              )
            ),`

**Comment by PlymouthRock** [comment] 2019-08-11 12:28
It looks like the missing step number and top number is hidden if you have a background color set.  So this is no longer an issue.

**Comment by diegoveloper** [comment] 2019-08-11 14:11
You can close the issue then :)

**Comment by PlymouthRock** [comment] 2019-08-12 10:45
I still have an issue with the bubble indicator being cut off at the top.  Is there some setting I'm missing?

**Comment by diegoveloper** [comment] 2019-08-12 16:07
Could you add a simple code to reproduce the issue? What version of the
package are you using?

**Comment by Dhuliang** [comment] 2019-08-16 06:07
@diegoveloper Thanks for great job ! But `tooltip` will be cut off .
![image](https://user-images.githubusercontent.com/40012139/63146926-2d72b980-c02f-11e9-8f4d-5a2e50ebb7f9.png)

**Comment by diegoveloper** [comment] 2019-08-16 06:24
That's because you are using a color on the parent container, check the
samples I put inside the library

**Comment by PlymouthRock** [comment] 2019-08-16 13:31
I made the container colors Transparent and it's still cut off.

**Comment by PlymouthRock** [comment] 2019-08-16 13:33
![chart-debug-cut-off](https://user-images.githubusercontent.com/2496106/63171106-de199280-c008-11e9-90f6-3f714cdfacb8.jpg)
Here's what it looks like in Debug mode.  I get that Red bar at the top.

**Comment by PlymouthRock** [comment] 2019-08-16 13:37
All of your samples use whole numbers.  Could it be that we are using decimals.  So instead of 10 we have 10.2.

**Comment by diegoveloper** [comment] 2019-08-16 15:45
Try using transparent color for the widget above the chart (hourly)

**Comment by PlymouthRock** [comment] 2019-08-16 15:55
Tried that.  I don't think it's a color issue.  I think the issue is the height calculation of the chart widget needs to be adjusted.  Let me create a simple test example and see if I can recreate the issue.  Maybe its my app.

**Comment by diegoveloper** [comment] 2019-08-17 04:05
ok let me know if I can help you

**Comment by angel1st** [comment] 2019-08-17 10:01
I have the similar issue, re bubble indicator, but it was cut off, when the chart scrolls to the leftmost side. See the screenshot below:
![Screenshot_1566035965](https://user-images.githubusercontent.com/8547131/63209871-1dbaaa00-c0ef-11e9-9c84-ce9583f723a5.png)

**Comment by PlymouthRock** [comment] 2019-08-17 10:35
It looks like it's a combination of things that is causing the bubble to be cut off:

1. Setting the container height to 250
2. Having the highest Value be a decimal number
3. Setting a larger font size on the Y Axis

I modified sample1 to duplicate the issue.

```
Widget sample1(BuildContext context) {
    return Center(
      child: Container(
        color: Colors.red,
        height: 250, //MediaQuery.of(context).size.height / 2,
        width: MediaQuery.of(context).size.width * 0.9,
        child: BezierChart(
          bezierChartScale: BezierChartScale.CUSTOM,
          xAxisCustomValues: const [0, 5, 10, 15, 20, 25, 30, 35],
          series: const [
            BezierLine(
              data: const [
                DataPoint<double>(value: 2, xAxis: 0),
                DataPoint<double>(value: 4, xAxis: 5),
                DataPoint<double>(value: 6, xAxis: 10),
                DataPoint<double>(value: 8, xAxis: 15),
                DataPoint<double>(value: 10.3, xAxis: 20),
                DataPoint<double>(value: 7, xAxis: 25),
                DataPoint<double>(value: 5, xAxis: 30),
                DataPoint<double>(value: 3, xAxis: 35),
              ],
            ),
          ],
          config: BezierChartConfig(
            verticalIndicatorStrokeWidth: 3.0,
            verticalIndicatorColor: Colors.black26,
            showVerticalIndicator: true,
            backgroundColor: Colors.red,
            displayYAxis: true,
            startYAxisFromNonZeroValue: false,
            stepsYAxis: 2,
            yAxisTextStyle: TextStyle(color: Colors.white, fontSize: 14),
          ),
        ),
      ),
    );
  }
```

**Comment by angel1st** [comment] 2019-08-17 18:58
I decided to file [a separate issue](https://github.com/aeyrium/bezier-chart/issues/42), since both cases seem different to me.

**Comment by diegoveloper** [comment] 2019-08-17 19:24
could you use `flutter packages upgrade` and try again?

**Comment by angel1st** [comment] 2019-08-17 19:45
I rather wait until [bubbleLabelCallback](https://github.com/aeyrium/bezier-chart/pull/40) is merged, so I would try to kill two birds with one stone :-)

**Comment by PlymouthRock** [comment] 2019-08-17 19:50
That fixed it!  Bubble Indicator is no longer cut off at the top.  Thanks!

**Closed** 2019-08-17 20:39 UTC
